name: fdc_aj_quiz_app
description: Quiz Application built on the Flutter Dev Camp

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1
  cloud_firestore: ^3.5.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  google_sign_in: ^5.4.2
  rxdart: ^0.27.5
  flutter_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.4.1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/covers/
